FROM golang:1.9-alpine

RUN mkdir -p /go/src/elyby/minecraft-skinsystem \
             /go/src/elyby/minecraft-skinsystem/data/capes \
 && ln -s /go/src/elyby/minecraft-skinsystem /go/src/app

WORKDIR /go/src/app

COPY ./ /go/src/app/

RUN apk add --no-cache git \
 && go get -u github.com/golang/dep/cmd/dep \
 && dep ensure \
 && go clean -i github.com/golang/dep \
 && rm -rf $GOPATH/src/github.com/golang/dep \
 && apk del git \
 && go build main.go \
 && mv main /usr/local/bin/minecraft-skinsystem

EXPOSE 80

ENTRYPOINT ["minecraft-skinsystem"]
CMD ["serve"]
